#ifndef __CLUSTER_CONFIG_H
#define __CLUSTER_CONFIG_H


#define CONFIG_DEBUG

// Настройки свойств задач

// использовать ли временные погрешности
// !!! в датасет нужно добавить отклонения
#define CONFIG_USE_TIME_VARIANCE


#undef  CONFIG_QUANTUM_TIME_RESOLUTION_PS
#define CONFIG_QUANTUM_TIME_RESOLUTION_NS
#undef  CONFIG_QUANTUM_TIME_RESOLUTION_US
#undef  CONFIG_QUANTUM_TIME_RESOLUTION_MS


#define CONFIG_QUANTUM_MEMORY_RESOLUTION_MB
#undef  CONFIG_QUANTUM_MEMORY_RESOLUTION_KB
#undef  CONFIG_QUANTUM_MEMORY_RESOLUTION_B


#undef  CONFIG_OUTPUT_SEQUENTIAL
#define CONFIG_OUTPUT_FRAME_BY_FRAME

#undef  CONFIG_OUTPUT_AUTO
#define  CONFIG_OUTPUT_MANUAL

/* #define CONFIG_OUTPUT_AUTO_PAUSE_TIME_US 1000000 */
#define CONFIG_OUTPUT_AUTO_PAUSE_TIME_US 0


#endif // ! __CLUSTER_CONFIG_H
