#ifndef __CLUSTER_CONFIG_H
#define __CLUSTER_CONFIG_H


#define CONFIG_DEBUG

// Настройки свойств задач

// использовать ли временные погрешности
// !!! в датасет нужно добавить отклонения
#define CONFIG_USE_TIME_VARIANCE


#undef  CONFIG_QUANTUM_TIME_RESOLUTION_PS
#define CONFIG_QUANTUM_TIME_RESOLUTION_NS
#undef  CONFIG_QUANTUM_TIME_RESOLUTION_US
#undef  CONFIG_QUANTUM_TIME_RESOLUTION_MS


#define CONFIG_QUANTUM_MEMORY_RESOLUTION_MB
#undef  CONFIG_QUANTUM_MEMORY_RESOLUTION_KB
#undef  CONFIG_QUANTUM_MEMORY_RESOLUTION_B


#endif // ! __CLUSTER_CONFIG_H
